### ISSUE TITLE
Undefined 

### ISSUE THREAD

**Issue by hemrshah** [kunaltyagi9/MERN-Stack-Projects#16]
When I m trying to upload file it says uncaught (in promise) TypeError: cannot read properties of undefined(reading 'path') at getImage(App.js:21:1)
Please help
Also it shows error while connecting to database
Please help 🙏

**Comment by second007** [comment]
syntax error watch video again

**Comment by kunaltyagi9** [comment]
Make sure the variable using which you are calling path has a value, it should not be undefined because undefined.path will give you this error.
