### ISSUE TITLE
socket.on('disconnect') handler not present in server

### ISSUE THREAD

**Issue by shiprachaubey** [kunaltyagi9/MERN-Stack-Projects#19]
The issue raised when frontend was trying to connect to backend 

The useEffect which was creating a socket on the frontend was also running a cleanup function which had socketServer.disconnect(); handler
but it is not present in the backend code .

frontend code issue line
 ` return () => {
            socketServer.disconnect();
        }`

**Comment by kunaltyagi9** [comment]
Please open a Pull Request where exactly this change is needed
