### ISSUE TITLE
Module not found: Error: Can't resolve './service/api'

### ISSUE THREAD

**Issue by kunjkhanpara** [kunaltyagi9/MERN-Stack-Projects#20]
Module not found: Error: Can't resolve './service/api' in 'E:\FileSharing\client\src'
ERROR in ./src/App.js 7:0-43
Module not found: Error: Can't resolve './service/api' in 'E:\FileSharing\client\src'

**Comment by kunaltyagi9** [comment]
Make sure you have a file with name api in the service folder. Also check the address while importing the api, if exist
