### ISSUE TITLE
_service_api__WEBPACK_IMPORTED_MODULE_1__.default.userSignup is not a function

### ISSUE THREAD

**Issue by Ritiknarhe** [kunaltyagi9/MERN-Stack-Projects#21]
_service_api__WEBPACK_IMPORTED_MODULE_1__.default.userSignup is not a function
TypeError: _service_api__WEBPACK_IMPORTED_MODULE_1__.default.userSignup is not a function

**Comment by sunilsinghx** [comment]
i was getting same error

its just when you we do export default API (do not put inside bracket)
same with importing it 
import API from '../../service/api.js'   (do not put inside bracket as import {API} from '../../service/api.js')

**Comment by logicalaryan** [comment]
Error in user-schema if   any changes were made.Delete the collection from mongodb an then restart the server and client part
