### ISSUE TITLE
Whatsapp Clone

### ISSUE THREAD

**Issue by mavsabharwal** [kunaltyagi9/MERN-Stack-Projects#3]
Hi,
I was wondering if you could share with me the Whatsapp clone videos that you posted on youtube as they seem to have been taken down from there. I was in the middle of watching them.
My email is coolparth1999@gmail.com

**Comment by mavsabharwal** [comment]
Hi,
Please reply, I need your help bro, can you please share those videos with me, please.

**Comment by kunaltyagi9** [comment]
Hi,

In an unfortunate incident, I lost my channel. I have created a new channel. I will post those videos soon on the new channel.
