### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by govind15496** [kunaltyagi9/MERN-Stack-Projects#8]
Hello, I'm trying to run these clones my system using command like "npm start" there are not running i've also search solution but did not any solutions please guid me thanks.

**Comment by govind15496** [comment]
I'm noob !

**Comment by GunjanShakya** [comment]
The first thing you should do is ensure that you have installed all the necessary dependencies for your project. If you followed the instructions correctly when cloning the repository, then all of the required dependencies should be included. You may type `npm i` in your terminal to install the necessary dependencies.
Once you have installed all the necessary dependencies, you can try running the command `npm start` again.

**Comment by jainss** [comment]
Hey @govind15496,  If you want to start this project here is some instruction you should follow.

1. Open the terminal of vs code in which you had cloned the file and then enter into the client directory by writing `cd client` and then run the command npm start. This command starts your client part.
2. Now open the new terminal by clicking on the '+' icon then write `cd server` to enter into the server directory and then write `npm start` to start your server.
3. wait for a few sec and your app run your default browser.


Here is the snap of the terminal:-

![image_2023-01-28_000652252](https://user-images.githubusercontent.com/59283222/215167576-aba347cc-8d43-4a84-9c75-41ff9c9e914c.png)
![image_2023-01-28_000712891](https://user-images.githubusercontent.com/59283222/215167642-6f2c6334-a9c5-4ae3-9a94-e54e3434f4cb.png)


Happy Coding!
